#!/bin/bash

# ansible-playbook -vvvv /root/openshift-ansible/playbooks/prerequisites.yml | tee output3.txt

# liga o debug
set -x

# indica para parar quando ocorrer qualquer erro
set -e

# Atualiza tudo
sudo yum update

# Instala pré-requisitos
sudo yum install wget unzip git
sudo yum install kernel-devel kernel-headers make patch gcc

# Install virtual box - https://linuxize.com/post/how-to-install-virtualbox-on-centos-7/
sudo wget https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo -P /etc/yum.repos.d
sudo yum update
sudo yum install VirtualBox-5.2
wget https://download.virtualbox.org/virtualbox/5.2.20/Oracle_VM_VirtualBox_Extension_Pack-5.2.20.vbox-extpack
sudo VBoxManage extpack install  Oracle_VM_VirtualBox_Extension_Pack-5.2.20.vbox-extpack
systemctl status vboxdrv

# Install Vagrant - https://linuxize.com/post/how-to-install-vagrant-on-centos-7/#installing-vagrant-on-centos
sudo yum install https://releases.hashicorp.com/vagrant/2.2.0/vagrant_2.2.0_x86_64.rpm

# Instala o openshift com o repo da 4linux
git clone https://github.com/4linux/4542
cd 4542
vagrant up
