#!/bin/bash

# https://linuxacademy.com/guide/15473-introduction-to-/

# listar todas 
iptables -S
iptables -L -v

# Adiciona as permissões de firewall
iptables -A INPUT -i eno1 -p udp --dport 137 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p udp --dport 138 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p tcp --dport 139 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p tcp --dport 445 -s 192.168.0.10/24 -j ACCEPT

# Flush
iptables -F

# 
iptables -t nat -F