#!/bin/bash

# Auto start: https://alvinalexander.com/linux/how-make-your-linux-iptables-firewall-automatically-start-after-reboot

# Após reiinicar o PC é necessário adicionar no IP table
iptables -A INPUT -i eno1 -p udp --dport 137 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p udp --dport 138 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p tcp --dport 139 -s 192.168.0.10/24 -j ACCEPT
iptables -A INPUT -i eno1 -p tcp --dport 445 -s 192.168.0.10/24 -j ACCEPT
iptables -F