#!/bin/bash

# https://www.techrepublic.com/article/how-to-set-up-quick-and-easy-file-sharing-with-samba/

# Instala os pacotes
yum install samba samba-client samba-common cifs-utils

# Cria o usuário do samba (pwd: samba)
addgroup smbgrp
useradd samba -G smbgrp
smbpasswd -a samba

# add other users (pwd: [idem])
usermod -a -G smbgrp root
smbpasswd -a root

usermod -a -G smbgrp junior
smbpasswd -a junior

# Cria a pasta no qual quer compartilhar
mkdir -p /files
chmod -R 0777 /files
chown -R samba:samba /files
chcon -R -t samba_share_t /files

# Faça um backup do arquivo de config
cp /etc/samba/smb.conf /etc/samba/smb.conf.orig

# Edita o arquivo do samba para compartilhar a pasta
vi /etc/samba/smb.conf

#******************************************************************#
#******************************************************************#
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.

[global]
# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.

[global]
        workgroup = WORKGROUP
        security = user
        netbios name = centos
        passdb backend = tdbsam
        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw

[homes]
        comment = Home Directories
        valid users = %S, %D%w%S
        browseable = No
        read only = No
        inherit acls = Yes

[printers]
        comment = All Printers
        path = /var/tmp
        printable = Yes
        create mask = 0600
        browseable = No

[print$]
        comment = Printer Drivers
        path = /var/lib/samba/drivers
        write list = @printadmin root
        force group = @printadmin
        create mask = 0664
        directory mask = 0775

[fileshare]
        comment = My storage
        path = /files
        browsable =yes
        writable = yes
        guest ok = yes
        read only = no
        valid users = @smbgrp
#******************************************************************#
#******************************************************************#

# Test a configuração
testparm

# Restart
systemctl enable smb.service 
systemctl enable nmb.service 
systemctl start smb.service 
systemctl start nmb.service

# Rara restarts após editar o arquivo
systemctl restart smb.service; systemctl restart nmb.service

# Testa se deu tudo certo
smbclient -L 192.168.0.10

# No windows, faça
\\192.168.0.10

# NAO FAZER SE TIVER USANDO OPENSHIFT, ELE ESTRAGA TUDO
        # IMPORTANTE: garanta que o firewall está ativo
        firewall-cmd --state
        systemctl enable firewalld
        systemctl start firewalld
        systemctl restart firewalld

        # Caso não consiga ativar, remova a mask
        systemctl unmask firewalld
        
        # Habilite o samba no firewall
        firewall-cmd --permanent --zone=public --add-service=samba
        firewall-cmd --reload
        firewall-cmd --list-all
# NAO FAZER SE TIVER USANDO OPENSHIFT, ELE ESTRAGA TUDO

# QUANDO TEM OPENSHIFT INSTALADO (É NECESSÁRIO A CADA REEBOT)
	# Adiciona as permissões de firewall
	iptables -A INPUT -i eno1 -p udp --dport 137 -s 192.168.0.10/24 -j ACCEPT
	iptables -A INPUT -i eno1 -p udp --dport 138 -s 192.168.0.10/24 -j ACCEPT
	iptables -A INPUT -i eno1 -p tcp --dport 139 -s 192.168.0.10/24 -j ACCEPT
	iptables -A INPUT -i eno1 -p tcp --dport 445 -s 192.168.0.10/24 -j ACCEPT
	iptables -F

	# iptables -t nat -F
	#systemctl start iptables 
	#systemctl stop iptables
	#systemctl restart iptables

        # Se nao funcionar, tente executar os passos (abrir a porta 137)
        #/centOS/open-ports
# QUANDO TEM OPENSHIFT INSTALADO
