#!/bin/bash

# https://stackoverflow.com/questions/20578039/difference-between-kvm-and-lxc
# https://www.cyberciti.biz/faq/how-to-install-kvm-on-centos-7-rhel-7-headless-server/

# O KVM representa os recursos de virtualização criados no próprio kernel do Linux. 
# Como já foi dito nas respostas anteriores, é o hypervisor do tipo 2, ou seja, não 
# está sendo executado em um bare metal.

