#!/bin/bash

sudo cat << EOF > /etc/docker/daemon.json
{
    "insecure-registries" : [ "172.30.0.0/16" ]
}
EOF
sudo service docker restart;
ip=$(hostname -I);
oc cluster up --routing-suffix=$ip --public-hostname=$ip;