apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: pvc-hostpath
      containers:
      - image: alpine
        name: alpine
        tty: true
        stdin: true
        volumeMounts:
        - name: cache
          mountPath: /tmp/cache