#!/bin/bash

# Criar um deploy config 
oc create deploy [name] --image=[image-name]
oc create deploy memcached --image=memcached

# Criar um deploy config CUIDADO - o parâmetro "-n" não funciona, ele sempre usará o projeto default
oc create deploy memcached --image=memcached -n [projeto]

# Remover deploy
oc delete deploy [projeto]
oc delete deploy memcached

#### TEMPLATE #####

# modelo de objeto
vi deploy.yml

# Conteudo (Obter do arquivo)
./deployment.object

# Criar o deploy
oc create -f deploy.yml