#!/bin/bash

# Habilita ou desabilita as métricas de HPA
sudo su
vi /etc/ansible/hosts
openshift_metrics_install_metrics = true|false

# Esta é a única necessária para o HPA
ansible-playbook /root/openshift-ansible/playbooks/metrics-server/config.yml

# Validar se o projeto "openshift-metrics-server" foi adicionado
oc get pods -n openshift-metrics-server

# Instala o Hawkular + Cassandra, é para os gráficos da dashboard.
ansible-playbook /root/openshift-ansible/playbooks/openshift-metrics/config.yml

# Aceitar o certificado no browser
https://hawkular-metrics.192.168.0.10.nip.io/hawkular/metrics

# Validar se o projeto "openshift-metrics" foi certificado
oc get pods -n openshift-infra

# Verificar o status do node (se retornar resultado é pq deu certo)
oc adm top nodes