#!/bin/bash

# Lista todos os volumes persistentes
oc get persistentvolumeclaim
oc get pvc

#### TEMPLATE do tipo HOST-PATH #####

# modelo de objeto (copia do arquivo abaixo)
vi pvc-files.yml

# Conteudo de um PVC
./persistentvolumeclain.yaml

# Criar o PV
oc create -f pvc-files.yml