apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  nfs:
    server: 192.168.0.10
    path: /files/nfs1