#!/bin/bash

# Lista todos os volumes persistentes
oc get persistentvolumeclaim
oc get pvc

#### TEMPLATE do tipo HOST-PATH #####

# modelo de objeto
vi pvc-files.yml

# Conteudo de um PVC
apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-hostpath"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  volumeName: "pv-hostpath"

# Criar o PV
oc create -f pvc-files.yml