apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
spec:
  replicas: 2
  selector:
    app: busybox
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: writer
        command: ['sh', '-c', 'while true; do date >> /empty-dir/list; sleep 5; done']
      - image: busybox
        name: reader
        command: ['sh', '-c', 'tail -f /empty-dir/list']