apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  nfs:
    server: 192.168.0.10
    path: /files/nfs2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs3
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  nfs:
    server: 192.168.0.10
    path: /files/nfs3