#!/bin/bash

# liga o debug
set -x

# indica para parar quando ocorrer qualquer erro
set -e

# Install Docker (https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository) OU https://get.docker.com/

sudo apt-get update
sudo apt-get install -y apt-transport-https;
sudo apt-get install -y ca-certificates;
sudo apt-get install -y curl;
sudo apt-get install -y gnupg-agent;
sudo apt-get install -y software-properties-common;
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Debug
# sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce;
sudo apt-get install -y docker-ce-cli;
sudo apt-get install -y containerd.io;
 
# sudo docker run hello-world
sudo usermod -aG docker $USER

# Instal OpenShift (https://medium.com/@maheshacharya_44641/install-openshift-origin-on-ubuntu-18-04-7b98773c2ee6; https://medium.com/@rodrigues552/entendendo-a-arquitetura-do-openshift-e-criando-um-cluster-local-ca5f59d9caaf)

wget https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz 
tar -zvxf openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
cd openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
sudo cp oc /usr/local/bin/
sudo wget -c -P /etc/docker https://raw.githubusercontent.com/juniorgasparotto/Scripts/master/openshift/daemon.json --no-cache
sudo service docker restart;
ip=$(hostname -I | cut -f 1 -d ' ');

# Precisa rodar como sudo, do contrário dá problema
sudo oc cluster up --routing-suffix=$ip --public-hostname=$ip;

# EM CASO DE ERRO O SERVIÇO
# sudo oc cluster down

# TENTE NOVAMENTE
# sudo oc cluster up --routing-suffix=<IP> --public-hostname=<IP>;

# Abrir no browser
# https://192.168.0.[IP]:8443/
# user admin: system
# pwd admin: admin

# user: developer
# pwd:  developer