#!/bin/bash

# DEBUG
# ansible-playbook -vvvv /root/openshift-ansible/playbooks/prerequisites.yml | tee output3.txt

# liga o debug
set -x

# indica para parar quando ocorrer qualquer erro
set -e

sudo yum update

echo -e "" > /etc/hosts
cat >> /etc/hosts <<EOF
127.0.0.1   okd.example.com okd
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.0.10 okd.example.com
EOF
cat /etc/hosts

yum install -y wget git vim PyYAML python-jinja2 python-paramiko python-setuptools python-six python2cryptography sshpass java-1.8.0-openjdk-headless python-passlib

rpm -i 'https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.5.15-1.el7.ans.noarch.rpm'
git clone -b release-3.11 --single-branch https://github.com/openshift/openshift-ansible /root/openshift-ansible
cp -f /root/openshift-ansible/ansible.cfg /etc/ansible/ansible.cfg

cd ~
git clone https://github.com/juniorgasparotto/Scripts.git
cp ~/Scripts/openshift/install/ansible-all-in-one/hosts /etc/ansible/hosts

ansible-playbook /root/openshift-ansible/playbooks/prerequisites.yml
ansible-playbook /root/openshift-ansible/playbooks/deploy_cluster.yml